var connectorId="";
var x1=0;
var y1=0;
var x2=0;
var y2=0;
var lineInitiated=0;
var lineCounter=0;
var startConnectorId="";
var endConnectorId="";
var startConnectorWireIds="";
var endConnectorWireIds="";
jsonObj = [];
var dropableCounter=0;
var idForDelete="";
//var backSvgCanvas;